#!/usr/bin/env bash
# install-vault.sh — deploy the `vault` skill on this Mac.
#
# What it does (idempotent):
#   1. Verifies dependencies (bw CLI, jq) or installs via brew on confirmation.
#   2. Prompts for VAULT_BW_SERVER + VAULT_BW_EMAIL, writes ~/.config/vault-skill/config.sh
#   3. Copies skills/vault/ to ~/.claude/skills/vault/   (and chmod +x scripts/vault)
#   4. Copies dotfiles/bw-secrets.zsh to ~/.config/bw-secrets.zsh
#   5. Idempotently adds source + PATH lines to ~/.zshrc
#   6. Configures the bw CLI to point at the new server
#   7. Prints the next-steps Keychain commands (which can't be automated — they
#      need your master password + browser-fetched API key)
#
# What it does NOT do:
#   - Touch your master password or API key (those go into Keychain manually)
#   - Log in to Bitwarden (you run `bw login` yourself)

set -euo pipefail

# Resolve repo root (this script lives in scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CYAN='\033[36m'; GREEN='\033[32m'; YELLOW='\033[33m'; RED='\033[31m'; RESET='\033[0m'
step()  { printf "${CYAN}==>${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}✓${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}!${RESET} %s\n" "$*"; }
fail()  { printf "${RED}✗${RESET} %s\n" "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
step "Check dependencies"

if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not installed. https://brew.sh"
fi

for pkg in bitwarden-cli jq; do
  if ! brew list "$pkg" >/dev/null 2>&1; then
    warn "$pkg not installed"
    read -rp "Install $pkg via brew? [Y/n] " ans
    [[ "${ans:-Y}" =~ ^[Nn] ]] || brew install "$pkg"
  fi
done
ok "bw $(bw --version 2>/dev/null | tail -1), jq $(jq --version)"

# ---------------------------------------------------------------------------
step "Configure server + email"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/vault-skill"
CONFIG_FILE="$CONFIG_DIR/config.sh"

if [[ -f "$CONFIG_FILE" ]]; then
  warn "Existing config at $CONFIG_FILE"
  read -rp "Overwrite? [y/N] " ans
  [[ "${ans:-N}" =~ ^[Yy] ]] || { ok "Keeping existing config"; SKIP_CONFIG=1; }
fi

if [[ -z "${SKIP_CONFIG:-}" ]]; then
  default_server="https://vault.example.com"
  default_email=$(git config --global user.email 2>/dev/null || echo "you@example.com")

  read -rp "Bitwarden / Vaultwarden server URL [$default_server]: " server
  server="${server:-$default_server}"

  read -rp "Account email [$default_email]: " email
  email="${email:-$default_email}"

  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# vault skill config (generated by install-vault.sh)
export VAULT_BW_SERVER="$server"
export VAULT_BW_EMAIL="$email"
EOF
  chmod 600 "$CONFIG_FILE"
  ok "Wrote $CONFIG_FILE"
fi

# Load whichever config we ended up with
# shellcheck disable=SC1090
source "$CONFIG_FILE"

# ---------------------------------------------------------------------------
step "Deploy skill files"
SKILL_DST="$HOME/.claude/skills/vault"
mkdir -p "$SKILL_DST/scripts"
cp -v "$REPO_ROOT/skills/vault/SKILL.md"        "$SKILL_DST/SKILL.md"
cp -v "$REPO_ROOT/skills/vault/README.md"       "$SKILL_DST/README.md"
cp -v "$REPO_ROOT/skills/vault/scripts/vault"   "$SKILL_DST/scripts/vault"
cp -v "$REPO_ROOT/skills/vault/scripts/lib.sh"  "$SKILL_DST/scripts/lib.sh"
chmod +x "$SKILL_DST/scripts/vault"
ok "Skill installed at $SKILL_DST"

# ---------------------------------------------------------------------------
step "Deploy bw-secrets.zsh helper"
HELPER_DST="${XDG_CONFIG_HOME:-$HOME/.config}/bw-secrets.zsh"
cp -v "$REPO_ROOT/dotfiles/bw-secrets.zsh" "$HELPER_DST"
ok "Helper installed at $HELPER_DST"

# ---------------------------------------------------------------------------
step "Wire into ~/.zshrc"
ZSHRC="$HOME/.zshrc"
touch "$ZSHRC"

ensure_line() {
  local line="$1"
  if ! grep -qF "$line" "$ZSHRC"; then
    printf '\n# Added by agent-toolkit/scripts/install-vault.sh\n%s\n' "$line" >> "$ZSHRC"
    ok "Added: $line"
  else
    ok "Already in .zshrc: $line"
  fi
}

ensure_line 'source "$HOME/.config/bw-secrets.zsh"'
ensure_line 'export PATH="$HOME/.claude/skills/vault/scripts:$PATH"'

# ---------------------------------------------------------------------------
step "Point bw CLI at $VAULT_BW_SERVER"
current_server=$(bw config --raw 2>/dev/null | jq -r '.["api.server"] // ""' 2>/dev/null || echo "")
if [[ "$current_server" != "$VAULT_BW_SERVER" ]]; then
  bw config server "$VAULT_BW_SERVER" >/dev/null
  ok "bw configured for $VAULT_BW_SERVER"
else
  ok "bw already pointing at $VAULT_BW_SERVER"
fi

# ---------------------------------------------------------------------------
step "Done with file deployment. Next steps you do yourself:"
HOST="${VAULT_BW_SERVER#http*://}"
cat <<EOF

  1. Log in to bw (interactive, prompts for master password + 2FA):

       bw login

  2. Store your master password in macOS Keychain (prompts hidden):

       security add-generic-password -s "$HOST" -a "$VAULT_BW_EMAIL" -w

  3. Get your personal API key from the web vault:

       open "$VAULT_BW_SERVER/#/settings/security/security-keys"

     Click "View API Key", copy client_id and client_secret.

  4. Store the API key in Keychain (replace placeholders with real values):

       security add-generic-password \\
         -s "$HOST-apikey" -a "$VAULT_BW_EMAIL" \\
         -w 'user.YOUR_CLIENT_ID:YOUR_CLIENT_SECRET'

  5. Verify everything:

       exec zsh
       vault setup

     You should see 8 OK lines ending with "All checks passed."

EOF
